# Generated by Django 6.0.7 on 2026-08-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habitstreak',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='habitaccomplishment',
            index=models.Index(fields=['date'], name='habittracke_date_68dec9_idx'),
        ),
    ]
