# Generated by Django 6.0.7 on 2026-08-06 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_habit_archived_at_habitstreak_archived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='type',
        ),
    ]
