# Generated by Django 6.0.7 on 2026-08-09 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0003_remove_achievement_icon_remove_achievement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='custom_category',
            field=models.CharField(blank=True, default='', max_length=63),
        ),
        migrations.AlterField(
            model_name='habit',
            name='notification_interval',
            field=models.PositiveIntegerField(default=0, help_text='Notify the user every X hours (1-24).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
