# Generated by Django 6.0.7 on 2026-08-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0004_habit_custom_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='habit',
            name='custom_category',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
