# Generated by Django 6.0.7 on 2026-08-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0005_alter_habit_color_alter_habit_custom_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
