# Generated by Django 6.0.7 on 2026-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0006_habit_last_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
