# Generated by Django 6.0.7 on 2026-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0007_habit_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
