# Generated by Django 6.0.7 on 2026-08-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='google_picture',
            field=models.URLField(blank=True),
        ),
    ]
