# Generated by Django 6.0.7 on 2026-08-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pushsubscription',
            constraint=models.UniqueConstraint(fields=('profile', 'endpoint'), name='unique_profile_endpoint'),
        ),
    ]
